
import img3 from './images/Allj.jpg'
import img4 from './images/Bridge.jpg'
import img5 from './images/Calculus.jpeg'
import img6 from './images/Camera.png'
import img7 from './images/Desk.jpg'
import img8 from './images/Disturbed.jpg'
import img9 from './images/Explosion.png'
import img10 from './images/Kigali.gif'
import img11 from './images/Lasers.jpg'
import img12 from './images/Mario.png'
import img13 from './images/Melodrama.jpg'
import img14 from './images/Pikachu.png'
import img15 from './images/Plant.jpg'
import img16 from './images/Sans.jpg'
import img17 from './images/Spectrum.jpg'
import img18 from './images/Spreadsheet.jpg'
import img19 from './images/Sugar.jpg'
import img20 from './images/Think.png'
import img21 from './images/Wizard.png'
import img22 from './images/concertHall.jpg'
import img23 from './images/cyrillicAlphabet.png'
import img24 from './images/ikeaBuilding.jpg'
import img25 from './images/mattSmithFez.jpg'
import img26 from './images/nightWatch.jpg'
import img27 from './images/pewdiepieVsTSeries.jpg'
import img28 from './images/questionMark.jpg'
import img29 from './images/scFiSoldier.jpg'
import img30 from './images/starryNight.jpg'
import img31 from './images/topHat.jpg'
import img32 from './images/whatsappLogo.jpg'
export default [  img3 , img4 , img5 , img6 ,img7 ,img8 , img9 , img10,  img11, img12,  img13  ,img14  ,img15  ,img16  ,img17  ,img18  ,img19  ,img20  ,img21  ,img22  ,img23 ,img24  ,img25  ,img26  ,img27  ,img28  ,img29  ,img30 ,img31 , img32  ]

